# Generated by Django 5.0.1 on 2024-01-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='start_date',
            field=models.DateField(),
        ),
    ]
