# Generated by Django 5.0.1 on 2024-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_academic_finish_date_alter_academic_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='academic',
            name='order_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academic',
            name='finish_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='start_date',
            field=models.CharField(max_length=15),
        ),
    ]
