# Generated by Django 5.0.1 on 2024-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_academic_options_academic_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='academic',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='academic',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='start_date',
            field=models.DateField(),
        ),
    ]
