# Generated by Django 5.0.1 on 2024-01-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_section', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=180, null=True),
        ),
    ]
